### ISSUE TITLE
ImportError: No module named resources

### ISSUE THREAD

**Issue by valeriucraciun** [victortrac/stratosphere#4]
Traceback (most recent call last):
  File "/usr/local/bin/stratosphere", line 11, in <module>
    load_entry_point('stratosphere==0.0.1', 'console_scripts', 'stratosphere')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 567, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2604, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2264, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2270, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/stratosphere/stratosphere.py", line 14, in <module>
    from stratosphere.resources import Template
ImportError: No module named resources

... this error is issued on running stratosphere command.

python --version
Python 2.7.6

pip --version
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)

Description:    Ubuntu 14.04.4 LTS

Does anybody have the same problem?

**Comment by victortrac** [comment]
@valeriucraciun I made some python2 incompatible changes. Can you try again in a python3 virtualenv?

**Comment by victortrac** [comment]
May have fixed it with this commit: https://github.com/victortrac/stratosphere/commit/6d19f73caa07842ef22ce561ba1409fffc02f75e

Let me know if that works for you.
